/**
 * `@sosb/schema` — block + site schemas, severity-tiered validation,
 * migration scaffold, and preserve-unknown-keys for forward compatibility.
 *
 * Tracking issue: #3.
 *
 * The runtime schemas are the single source of truth: TypeScript types are
 * derived via `z.infer`, and there are no hand-maintained type aliases that
 * could drift from the schema definitions.
 */

// Site spine
export { PageSchema, SITE_SCHEMA_VERSION, SiteSchema, parseSite } from "./site.js";
export type { Org, Page, Site, Theme } from "./site.js";

// Page slug rules (multi-page support)
export { SLUG_PATTERN, checkSlug, isValidSlug } from "./slug.js";
export type { SlugValidationFailure } from "./slug.js";

// Blocks
export {
  AssetRefSchema,
  BlockEnvelopeSchema,
  CONTACT_CARD_BLOCK_VERSION,
  CTA_BANNER_BLOCK_VERSION,
  CUSTOM_HTML_BLOCK_VERSION,
  ContactCardBlockSchema,
  ContactCardDataSchema,
  CtaBannerAssetRefSchema,
  CtaBannerBlockSchema,
  CtaBannerDataSchema,
  CtaButtonSchema,
  CtaButtonStyleSchema,
  CustomHtmlBlockSchema,
  CustomHtmlDataSchema,
  DEFAULT_EVENT_SORT,
  DEFAULT_PAST_BEHAVIOR,
  DOCUMENT_DOWNLOADS_BLOCK_VERSION,
  DocumentAssetRefSchema,
  DocumentDownloadFileSchema,
  DocumentDownloadsBlockSchema,
  DocumentDownloadsDataSchema,
  EMBED_BLOCK_VERSION,
  EMBED_PROVIDERS,
  EMBED_URL_PATTERNS,
  EVENT_LIST_BLOCK_VERSION,
  EmbedBlockSchema,
  EmbedDataSchema,
  EventEntrySchema,
  EventListBlockSchema,
  EventListDataSchema,
  FAQ_BLOCK_VERSION,
  FaqBlockSchema,
  FaqDataSchema,
  FaqItemSchema,
  GalleryImageSchema,
  HERO_BLOCK_VERSION,
  HeroBlockSchema,
  HeroDataSchema,
  IMAGE_GALLERY_BLOCK_VERSION,
  ImageGalleryBlockSchema,
  ImageGalleryDataSchema,
  KnownBlockSchemas,
  PersonPhotoSchema,
  QUOTE_BLOCK_VERSION,
  QuoteBlockSchema,
  QuoteDataSchema,
  RICH_TEXT_ALIGNMENTS,
  RICH_TEXT_BLOCK_VERSION,
  RichTextBlockSchema,
  RichTextDataSchema,
  TEAM_GRID_BLOCK_VERSION,
  TeamGridBlockSchema,
  TeamGridDataSchema,
  VALUE_LIST_BLOCK_VERSION,
  VALUE_LIST_COLUMNS,
  VALUE_LIST_ICON_NAMES,
  VALUE_LIST_LAYOUTS,
  ValueListBlockSchema,
  ValueListDataSchema,
  ValueListItemSchema,
  PARTNER_LOGOS_BLOCK_VERSION,
  PARTNER_LOGOS_PRESENTATIONS,
  PartnerLogosBlockSchema,
  PartnerLogosDataSchema,
  isKnownBlockType,
  isValidEmbedUrl,
  ACTIVITIES_LIST_BLOCK_VERSION,
  ActivitiesListBlockSchema,
  ActivitiesListDataSchema,
  ActivitiesListLayoutSchema,
  ActivityImageRefSchema,
  ActivityItemSchema,
  ActivityLinkSchema,
} from "./blocks/index.js";
export type {
  AssetRef,
  AssetRefValue,
  AssetRefLike,
  BlockEnvelope,
  ContactCardBlock,
  ContactCardData,
  ContactCardMapEmbed,
  CtaBannerAssetRef,
  CtaBannerBlock,
  CtaBannerData,
  CtaButton,
  CtaButtonStyle,
  CustomHtmlBlock,
  CustomHtmlData,
  DocumentAssetRef,
  DocumentDownloadFile,
  DocumentDownloadsBlock,
  DocumentDownloadsData,
  EmbedBlock,
  EmbedData,
  EmbedProvider,
  EventEntry,
  EventListBlock,
  EventListData,
  EventPastBehavior,
  EventSortBy,
  FaqBlock,
  FaqData,
  FaqItem,
  GalleryImage,
  HeroBlock,
  HeroData,
  ImageGalleryBlock,
  ImageGalleryData,
  KnownBlockType,
  QuoteBlock,
  QuoteData,
  Partner,
  PartnerLogosBlock,
  PartnerLogosData,
  PartnerLogosPresentation,
  TeamGridBlock,
  TeamGridData,
  TeamGridPerson,
  TeamGridPersonPhoto,
  TeamGridSocialLink,
  ValueListBlock,
  ValueListColumns,
  ValueListData,
  ValueListIconName,
  ValueListItem,
  ValueListLayout,
  ActivitiesListBlock,
  ActivitiesListData,
  ActivitiesListLayout,
  ActivityImageRef,
  ActivityItem,
  ActivityLink,
  RichTextBlock,
  RichTextAlignment,
  RichTextData,
} from "./blocks/index.js";

// Validation
export { KNOWN_THEME_IDS_FOR_VALIDATION, validate, validateBlock } from "./validate.js";
export type { Severity, ValidationIssue, ValidationResult } from "./validate.js";

// Migration
export { BLOCK_MIGRATIONS, SITE_MIGRATIONS, migrateBlock, migrateSite } from "./migrate.js";
export type {
  BlockMigration,
  BlockMigrationResult,
  SiteMigration,
  SiteMigrationResult,
} from "./migrate.js";
