/**
 * Asociația Studențească Demo — curated demo template (issue #34).
 *
 * Loaded by the welcome screen's "Start from template" path (issue #32).
 * The data file ships a complete two-page Romanian site that exercises every
 * v1 block type (#9-#22) so the demo lights up automatically as block
 * implementations land. Blocks whose type is not yet in
 * `KnownBlockSchemas` round-trip through the BlockEnvelope (forward-compat
 * contract) and render as HTML comment placeholders today.
 *
 * Quality posture: the Romanian copy is **AI-drafted**; the maintainer's
 * note on issue #34 explicitly tags it for native review before public demo
 * use. The bar this file targets is "plausible enough to demo," not
 * "publication-ready Romanian."
 *
 * `[de înlocuit]` markers from the PRD live in `replaceMarkers` below and
 * are surfaced by the editor only — they never appear inside the data file
 * itself, so they cannot leak into the rendered HTML.
 */
import type { Site } from "@sosb/schema";
import data from "./data.json" with { type: "json" };

export const ASOCIATIA_STUDENTEASCA_DEMO_ID = "asociatia-studenteasca-demo" as const;

/**
 * Raw site data. Imported from JSON so the template stays editable as plain
 * data and round-trips through the schema's preserve-unknown-keys contract
 * without relying on TypeScript helpers at runtime.
 */
export const asociatiaStudenteascaDemoData: Site = data as Site;

/**
 * One `[de înlocuit]` marker — a hint the editor surfaces inline ("swap
 * this for your real content") without ever leaking into the rendered HTML.
 *
 * `path` is a JSON-pointer-flavoured string that names the field to swap;
 * `code` is a stable identifier the editor's i18n layer can key off.
 */
export interface ReplaceMarker {
  /** Stable identifier (e.g. for editor i18n / analytics). */
  readonly code: string;
  /** Path-into-site notation pointing at the field to swap. */
  readonly path: string;
  /** Free-form English hint text shown to the editor user. */
  readonly hint: string;
}

/**
 * Asset credit notice. The demo uses placeholder asset *paths*; the actual
 * binary assets are out of scope for issue #34 (#37 owns asset packaging).
 * When real CC0 photos land at these paths, the credits per item land here
 * too.
 */
export interface AssetCredits {
  readonly license: "CC0";
  readonly notice: string;
  /**
   * Per-asset credit entries. Empty in v1 because the placeholders are not
   * yet bound to real photographers; populated by #37 / a future asset PR.
   */
  readonly entries: ReadonlyArray<{
    readonly path: string;
    readonly credit?: string;
    readonly source?: string;
  }>;
}

export interface AsociatiaStudenteascaDemoMetadata {
  /** True — copy was generated by an AI agent during issue #34. */
  readonly aiDrafted: true;
  /** True — pending review by a Romanian native speaker before public use. */
  readonly nativeReviewPending: true;
  /** `[de înlocuit]` markers shown inline by the editor. */
  readonly replaceMarkers: readonly ReplaceMarker[];
  /** Credit notice for the placeholder asset paths. */
  readonly assetCredits: AssetCredits;
}

export const asociatiaStudenteascaDemoMetadata: AsociatiaStudenteascaDemoMetadata = {
  aiDrafted: true,
  nativeReviewPending: true,
  assetCredits: {
    license: "CC0",
    notice:
      "Demo template references CC0 placeholder asset paths only; bundled binary assets land in #37. Replace with your organisation's own photos before publishing.",
    entries: [],
  },
  replaceMarkers: [
    {
      code: "org.name",
      path: "/org/name",
      hint: "Replace with your organisation's official name.",
    },
    {
      code: "org.tagline",
      path: "/org/tagline",
      hint: "Replace with a short tagline that captures your organisation's voice.",
    },
    {
      code: "org.email",
      path: "/org/email",
      hint: "Swap the example contact address for your real one.",
    },
    {
      code: "org.phone",
      path: "/org/phone",
      hint: "Replace the placeholder phone number with your real contact number.",
    },
    {
      code: "org.address",
      path: "/org/address",
      hint: "Replace the placeholder address with your real headquarters / mailing address.",
    },
    {
      code: "team.members",
      path: "/pages[slug=despre]/blocks[type=teamGrid]/data/members",
      hint: "Replace the placeholder team members with your current leadership.",
    },
    {
      code: "partners.items",
      path: "/pages[slug=acasa]/blocks[type=partnerLogos]/data/items",
      hint: "Replace the placeholder partner logos with your real sponsors.",
    },
    {
      code: "events.items",
      path: "/pages[slug=acasa]/blocks[type=eventList]/data/items",
      hint: "Replace the example events with your organisation's real schedule.",
    },
    {
      code: "documents.items",
      path: "/pages[slug=despre]/blocks[type=documentDownloads]/data/items",
      hint: "Replace the placeholder document links with your real public files.",
    },
    {
      code: "embed.url",
      path: "/pages[slug=despre]/blocks[type=embed]/data/url",
      hint: "Replace with a real, allow-listed embed URL (YouTube, Spotify, etc.).",
    },
  ],
};

/**
 * Public template descriptor. The welcome screen's `Start from template`
 * action (#32) reads this shape to build the picker affordance.
 */
export interface TemplateDescriptor {
  readonly id: string;
  readonly name: string;
  readonly description: string;
  readonly data: Site;
  readonly metadata: AsociatiaStudenteascaDemoMetadata;
}

export const ASOCIATIA_STUDENTEASCA_DEMO: TemplateDescriptor = {
  id: ASOCIATIA_STUDENTEASCA_DEMO_ID,
  name: "Asociația Studențească Demo",
  description:
    "A two-page Romanian student association demo covering every v1 block type. AI-drafted; native review recommended before public use.",
  data: asociatiaStudenteascaDemoData,
  metadata: asociatiaStudenteascaDemoMetadata,
};
