/**
 * Generate the service-worker source script as a string.
 *
 * The host (the build pipeline, the dev harness, or an Electron shell) calls
 * this function and writes the result to a known URL — typically `/sw.js`
 * relative to the SPA scope. The page-side `registerServiceWorker()` helper
 * then registers that URL.
 *
 * Caching strategy: **cache-first with a per-version namespace.**
 *
 *   - On `install`: open `${prefix}-${version}` and `addAll(precacheUrls)`.
 *     Calls `skipWaiting()` so the new worker is ready to activate as soon
 *     as the page closes its current controller.
 *   - On `activate`: enumerate `caches.keys()`, delete any that share the
 *     prefix but a different version (so a version bump frees space). Then
 *     `clients.claim()` so the new worker controls the existing tab without
 *     a hard reload.
 *   - On `fetch`: serve from the cache if present; fall back to the network
 *     and store the response in the cache for next time. Responses to
 *     non-GET requests are not cached.
 *
 * The "new version available" toast in the host UI is driven by
 * `registerServiceWorker(opts).onUpdateAvailable` — that callback fires
 * when a new SW reaches the installed state behind the active controller.
 * The toast triggers a `applyUpdate()` which sends `SKIP_WAITING` and
 * reloads. The script supports that protocol via a `message` listener for
 * the `SKIP_WAITING` keyword.
 *
 * The script never imports any module specifier — it's a self-contained
 * blob that runs inside `ServiceWorkerGlobalScope`.
 */

export interface ServiceWorkerScriptOptions {
  /**
   * Version stamp embedded in the cache name. Bump this on every deploy so
   * the new SW invalidates the old cache and takes ownership.
   */
  readonly version: string;
  /**
   * URLs to precache on install. Should include at least the SPA shell:
   * `/`, the main JS bundle, the main CSS bundle, the editor's HTML.
   */
  readonly precacheUrls: readonly string[];
  /**
   * Prefix for the cache name. Defaults to `"sosb"`. Multiple SOSB
   * deployments hosted under the same origin can pass distinct prefixes to
   * avoid clobbering each other's caches.
   */
  readonly cacheNamePrefix?: string;
}

const DEFAULT_PREFIX = "sosb";

/**
 * Build the worker source. Output is deterministic across calls with the
 * same options so the host can hash it for an integrity check.
 */
export function buildServiceWorkerScript(options: ServiceWorkerScriptOptions): string {
  const prefix = options.cacheNamePrefix ?? DEFAULT_PREFIX;
  const version = options.version;
  const cacheName = `${prefix}-${version}`;
  // JSON.stringify keeps the precache list a literal JS array of strings,
  // safe against quote-injection from caller-supplied URLs.
  const precacheLiteral = JSON.stringify([...options.precacheUrls]);
  const prefixLiteral = JSON.stringify(prefix);
  const cacheNameLiteral = JSON.stringify(cacheName);

  return `/* sosb service worker — generated by @sosb/browser-shell */
const CACHE_NAME = ${cacheNameLiteral};
const CACHE_PREFIX = ${prefixLiteral};
const PRECACHE_URLS = ${precacheLiteral};

self.addEventListener("install", (event) => {
  event.waitUntil(
    (async () => {
      const cache = await caches.open(CACHE_NAME);
      await cache.addAll(PRECACHE_URLS);
      await self.skipWaiting();
    })(),
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    (async () => {
      const names = await caches.keys();
      await Promise.all(
        names
          .filter((n) => n.startsWith(CACHE_PREFIX + "-") && n !== CACHE_NAME)
          .map((n) => caches.delete(n)),
      );
      await self.clients.claim();
    })(),
  );
});

self.addEventListener("fetch", (event) => {
  const req = event.request;
  if (req.method !== "GET") return;
  event.respondWith(
    (async () => {
      const cache = await caches.open(CACHE_NAME);
      const cached = await cache.match(req);
      if (cached !== undefined) {
        // Refresh the cache in the background but serve the cached copy now.
        event.waitUntil(
          (async () => {
            try {
              const fresh = await fetch(req);
              if (fresh && fresh.ok) await cache.put(req, fresh.clone());
            } catch (_e) {
              /* offline — keep the cached copy */
            }
          })(),
        );
        return cached;
      }
      try {
        const fresh = await fetch(req);
        if (fresh && fresh.ok) await cache.put(req, fresh.clone());
        return fresh;
      } catch (_e) {
        // Offline AND not in cache: re-throw so the page can show its own
        // offline UI. The PRD does not specify a fallback page.
        throw _e;
      }
    })(),
  );
});

self.addEventListener("message", (event) => {
  if (event.data && event.data.type === "SKIP_WAITING") {
    self.skipWaiting();
  }
});
`;
}
