// Font codegen: reads subset woff2 from the pinned @fontsource devDeps and
// emits two committed, deterministic generated TS files:
//   packages/renderer/src/fonts/font-bytes.generated.ts  (base64 bytes)
//   packages/renderer/src/fonts/fonts.generated.ts        (typed manifest)
//
// The base64 is the committed/renderable form — we do NOT commit raw woff2.
// Run via `pnpm gen:fonts`. Use `--check` in CI/tests to guard against drift.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, "..");
const FONTSOURCE_DIR = join(REPO_ROOT, "packages", "renderer", "node_modules", "@fontsource");
const FONTS_OUT_DIR = join(REPO_ROOT, "packages", "renderer", "src", "fonts");
const BYTES_OUT = join(FONTS_OUT_DIR, "font-bytes.generated.ts");
const FACES_OUT = join(FONTS_OUT_DIR, "fonts.generated.ts");

const SUBSETS = ["latin", "latin-ext"];

// family display name -> { pkg, weights }
const FONTS = [
  { family: "Archivo", pkg: "archivo", weights: [700, 800] },
  { family: "Space Grotesk", pkg: "space-grotesk", weights: [500, 700] },
  { family: "Fraunces", pkg: "fraunces", weights: [600] },
  { family: "Source Serif 4", pkg: "source-serif-4", weights: [600, 700] },
  { family: "Inter", pkg: "inter", weights: [400, 500, 600, 700] },
];

/**
 * Extract the `unicode-range` for a specific woff2 file from the per-weight
 * @fontsource CSS (e.g. inter/400.css). Each @font-face block carries its own
 * unicode-range; we match the block whose `src` references the target file.
 *
 * Note: @fontsource's per-SUBSET css (latin.css / latin-ext.css) does NOT carry
 * unicode-range — only the per-WEIGHT css files do — so we read those.
 */
function readUnicodeRange(pkg, weight, file) {
  const cssPath = join(FONTSOURCE_DIR, pkg, `${weight}.css`);
  const css = readFileSync(cssPath, "utf8");
  // Split into @font-face blocks and find the one whose src names our file.
  const blocks = css.split("@font-face");
  for (const block of blocks) {
    if (!block.includes(file)) continue;
    const m = block.match(/unicode-range:\s*([^;]+);/);
    if (m) return m[1].trim();
  }
  throw new Error(`No unicode-range found for ${file} in ${pkg}/${weight}.css`);
}

/**
 * Pure data builder. Reads woff2 bytes + unicode-ranges from @fontsource and
 * returns deterministically-ordered { base64, manifest }.
 */
export function buildFontData() {
  const manifest = [];
  const base64 = {};

  for (const { family, pkg, weights } of FONTS) {
    for (const weight of weights) {
      for (const subset of SUBSETS) {
        const file = `${pkg}-${subset}-${weight}-normal.woff2`;
        const filePath = join(FONTSOURCE_DIR, pkg, "files", file);
        const bytes = readFileSync(filePath);
        base64[file] = bytes.toString("base64");
        const unicodeRange = readUnicodeRange(pkg, weight, file);
        manifest.push({ family, weight, style: "normal", subset, file, unicodeRange });
      }
    }
  }

  // Deterministic ordering: manifest by family, weight, subset.
  manifest.sort(
    (a, b) =>
      a.family.localeCompare(b.family) || a.weight - b.weight || a.subset.localeCompare(b.subset),
  );

  // Deterministic ordering: base64 keys sorted.
  const sortedBase64 = {};
  for (const key of Object.keys(base64).sort()) {
    sortedBase64[key] = base64[key];
  }

  return { base64: sortedBase64, manifest };
}

const GEN_HEADER =
  "/* eslint-disable */\n" +
  "// @generated by scripts/gen-fonts.mjs — do not edit. Run `pnpm gen:fonts`.\n";

function renderBytesFile(base64) {
  const entries = Object.entries(base64)
    .map(([file, b64]) => `  ${JSON.stringify(file)}: ${JSON.stringify(b64)},`)
    .join("\n");
  return (
    GEN_HEADER +
    "\n" +
    "export const FONT_WOFF2_BASE64: Record<string, string> = {\n" +
    entries +
    "\n};\n"
  );
}

function renderFacesFile(manifest) {
  const entries = manifest
    .map(
      (f) =>
        "  {\n" +
        `    family: ${JSON.stringify(f.family)},\n` +
        `    weight: ${f.weight},\n` +
        `    style: "normal",\n` +
        `    subset: ${JSON.stringify(f.subset)},\n` +
        `    file: ${JSON.stringify(f.file)},\n` +
        `    unicodeRange: ${JSON.stringify(f.unicodeRange)},\n` +
        "  },",
    )
    .join("\n");
  return (
    GEN_HEADER +
    "\n" +
    "export interface GeneratedFontFace {\n" +
    "  family: string;\n" +
    "  weight: number;\n" +
    '  style: "normal";\n' +
    '  subset: "latin" | "latin-ext";\n' +
    "  file: string;\n" +
    "  unicodeRange: string;\n" +
    "}\n" +
    "\n" +
    "export const GENERATED_FONT_FACES: GeneratedFontFace[] = [\n" +
    entries +
    "\n];\n"
  );
}

function writeGenerated() {
  const { base64, manifest } = buildFontData();
  mkdirSync(FONTS_OUT_DIR, { recursive: true });
  writeFileSync(BYTES_OUT, renderBytesFile(base64));
  writeFileSync(FACES_OUT, renderFacesFile(manifest));
  return { base64, manifest };
}

function checkGenerated() {
  const { base64, manifest } = buildFontData();
  const expectedBytes = renderBytesFile(base64);
  const expectedFaces = renderFacesFile(manifest);

  const mismatches = [];
  for (const [label, path, expected] of [
    ["font-bytes.generated.ts", BYTES_OUT, expectedBytes],
    ["fonts.generated.ts", FACES_OUT, expectedFaces],
  ]) {
    let actual;
    try {
      actual = readFileSync(path, "utf8");
    } catch {
      mismatches.push(`${label}: MISSING (file not found at ${path})`);
      continue;
    }
    if (actual !== expected) {
      mismatches.push(
        `${label}: OUT OF DATE (committed length ${actual.length} vs generated ${expected.length})`,
      );
    }
  }

  if (mismatches.length > 0) {
    console.error("gen:fonts --check FAILED:");
    for (const m of mismatches) console.error("  - " + m);
    console.error("Run `pnpm gen:fonts` and commit the result.");
    process.exit(1);
  }
  console.log(
    `gen:fonts --check OK (${manifest.length} faces, ${Object.keys(base64).length} woff2)`,
  );
}

const isCheck = process.argv.includes("--check");
if (isCheck) {
  checkGenerated();
} else {
  const { base64, manifest } = writeGenerated();
  console.log(
    `gen:fonts wrote ${manifest.length} faces + ${Object.keys(base64).length} woff2 base64 entries`,
  );
  console.log(`  -> ${BYTES_OUT}`);
  console.log(`  -> ${FACES_OUT}`);
}
